project:
  title: "report"
  output-dir: "_output"

lang: ru-RU
standalone: true
self-contained: true

# Общее оформление
number-sections: true
toc: true
toc-title: "Содержание"
toc-depth: 2

# Кросс-ссылки
crossref:
  lof-title: "Список иллюстраций"
  lot-title: "Список таблиц"
  lol-title: "Листинги"

# Библиография
bibliography:
  - bib/cite.bib
csl: _resources/csl/gost-r-7-0-5-2008-numeric.csl

format:

  pdf:
    pdf-engine: xelatex
    toc: true
    number-sections: true
    toc-depth: 2
    lof: true       # Список иллюстраций
    lot: true       # Список таблиц
    colorlinks: false

    # Параметры документа
    documentclass: scrreprt
    papersize: a4
    fontsize: 12pt
    linestretch: 1.5
    geometry: "top=2.5cm, bottom=2.5cm, left=2.5cm, right=2.5cm"

    # Языки
    babel-lang: russian
    babel-otherlangs: english

    # BibLaTeX
    cite-method: biblatex
    biblatexoptions:
      - backend=biber
      - autolang=other*
      - sorting=none

    # Дополнения
    csquotes: true
    indent: true

    include-in-header:
      - file: _assets/preamble.tex

  docx:
    toc: true
    number-sections: true
    toc-depth: 2
